import type { InvoiceTemplate } from '../../types'

export const templates: InvoiceTemplate[] = [
  {
    id: 'blossom',
    name: 'بهاری',
    nameEn: 'Blossom',
    preview: '🌸',
    customization: {
      primaryColor: '#FF8FAB',
      fontFamily: 'Vazirmatn',
      fontSize: 12,
      showLogo: true,
      showSignature: true,
      showQR: true,
      showPaymentInfo: true,
      logoPosition: 'right',
      watermark: '',
    },
  },
  {
    id: 'rose-gold',
    name: 'رز گلد',
    nameEn: 'Rose Gold',
    preview: '🌹',
    customization: {
      primaryColor: '#FFD700',
      fontFamily: 'Vazirmatn',
      fontSize: 12,
      showLogo: true,
      showSignature: true,
      showQR: true,
      showPaymentInfo: true,
      logoPosition: 'right',
      watermark: '',
    },
  },
  {
    id: 'lavender',
    name: 'رویای اسطوخودوس',
    nameEn: 'Lavender Dream',
    preview: '💜',
    customization: {
      primaryColor: '#C9A7EB',
      fontFamily: 'Vazirmatn',
      fontSize: 12,
      showLogo: true,
      showSignature: true,
      showQR: true,
      showPaymentInfo: true,
      logoPosition: 'right',
      watermark: '',
    },
  },
  {
    id: 'minimal-chic',
    name: 'مینیمال شیک',
    nameEn: 'Minimal Chic',
    preview: '✨',
    customization: {
      primaryColor: '#FF8FAB',
      fontFamily: 'Vazirmatn',
      fontSize: 11,
      showLogo: true,
      showSignature: false,
      showQR: false,
      showPaymentInfo: true,
      logoPosition: 'right',
      watermark: '',
    },
  },
  {
    id: 'marble-luxe',
    name: 'لوکس مرمری',
    nameEn: 'Marble Luxe',
    preview: '🏛️',
    customization: {
      primaryColor: '#D4C9E1',
      fontFamily: 'Vazirmatn',
      fontSize: 12,
      showLogo: true,
      showSignature: true,
      showQR: true,
      showPaymentInfo: true,
      logoPosition: 'center',
      watermark: '',
    },
  },
  {
    id: 'pastel-wave',
    name: 'موج پاستلی',
    nameEn: 'Pastel Wave',
    preview: '🌈',
    customization: {
      primaryColor: '#A8D8EA',
      fontFamily: 'Vazirmatn',
      fontSize: 12,
      showLogo: true,
      showSignature: true,
      showQR: true,
      showPaymentInfo: true,
      logoPosition: 'right',
      watermark: '',
    },
  },
  {
    id: 'classic-formal',
    name: 'کلاسیک رسمی',
    nameEn: 'Classic Formal',
    preview: '📋',
    customization: {
      primaryColor: '#6B7280',
      fontFamily: 'Vazirmatn',
      fontSize: 11,
      showLogo: true,
      showSignature: true,
      showQR: false,
      showPaymentInfo: true,
      logoPosition: 'right',
      watermark: '',
    },
  },
  {
    id: 'dark-elegance',
    name: 'شب‌نورد',
    nameEn: 'Dark Elegance',
    preview: '🌙',
    customization: {
      primaryColor: '#FF2D95',
      fontFamily: 'Vazirmatn',
      fontSize: 12,
      showLogo: true,
      showSignature: true,
      showQR: true,
      showPaymentInfo: true,
      logoPosition: 'right',
      watermark: '',
    },
  },
  {
    id: 'botanical',
    name: 'گیاهی',
    nameEn: 'Botanical',
    preview: '🌿',
    customization: {
      primaryColor: '#7BC4A0',
      fontFamily: 'Vazirmatn',
      fontSize: 12,
      showLogo: true,
      showSignature: true,
      showQR: true,
      showPaymentInfo: true,
      logoPosition: 'right',
      watermark: '',
    },
  },
  {
    id: 'geometric',
    name: 'هندسی',
    nameEn: 'Geometric',
    preview: '🔷',
    customization: {
      primaryColor: '#F4A261',
      fontFamily: 'Vazirmatn',
      fontSize: 12,
      showLogo: true,
      showSignature: true,
      showQR: true,
      showPaymentInfo: true,
      logoPosition: 'right',
      watermark: '',
    },
  },
  {
    id: 'vintage-paper',
    name: 'کاغذ کهنه',
    nameEn: 'Vintage Paper',
    preview: '📜',
    customization: {
      primaryColor: '#C4956A',
      fontFamily: 'Vazirmatn',
      fontSize: 12,
      showLogo: true,
      showSignature: true,
      showQR: true,
      showPaymentInfo: true,
      logoPosition: 'right',
      watermark: '',
    },
  },
  {
    id: 'gradient-pop',
    name: 'گرادینت پاپ',
    nameEn: 'Gradient Pop',
    preview: '🎨',
    customization: {
      primaryColor: '#FF6B6B',
      fontFamily: 'Vazirmatn',
      fontSize: 12,
      showLogo: true,
      showSignature: true,
      showQR: true,
      showPaymentInfo: true,
      logoPosition: 'right',
      watermark: '',
    },
  },
]
